//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaidarGadget.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RaidarGadget.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///(data is extremely
        ///vulnerable, react
        ///immediately!).
        /// </summary>
        internal static string Criticality_critical {
            get {
                return ResourceManager.GetString("Criticality_critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        ///Data is most certainly lost..
        /// </summary>
        internal static string Criticality_fatal {
            get {
                return ResourceManager.GetString("Criticality_fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///(this may take a few hours).
        /// </summary>
        internal static string Criticality_temporary {
            get {
                return ResourceManager.GetString("Criticality_temporary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///(take measures, you are
        ///at risk of losing data).
        /// </summary>
        internal static string Criticality_vulnerable {
            get {
                return ResourceManager.GetString("Criticality_vulnerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc awaiting recovery.
        /// </summary>
        internal static string Status_awaiting_recovery {
            get {
                return ResourceManager.GetString("Status_awaiting_recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device has failed.
        /// </summary>
        internal static string Status_dead {
            get {
                return ResourceManager.GetString("Status_dead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is operating incorrectly
        ///or failed.
        /// </summary>
        internal static string Status_default_not_ok {
            get {
                return ResourceManager.GetString("Status_default_not_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk malfunction:
        ///turn off ReadyNAS ASAP.
        /// </summary>
        internal static string Status_disk_not_ok {
            get {
                return ResourceManager.GetString("Status_disk_not_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device has failed.
        /// </summary>
        internal static string Status_fail {
            get {
                return ResourceManager.GetString("Status_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan malfunction:
        ///turn off ReadyNAS ASAP,
        ///otherwise device may overheat.
        /// </summary>
        internal static string Status_fan_not_ok {
            get {
                return ResourceManager.GetString("Status_fan_not_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple disk failures detected.
        /// </summary>
        internal static string Status_life_support {
            get {
                return ResourceManager.GetString("Status_life_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No device attached.
        /// </summary>
        internal static string Status_not_present {
            get {
                return ResourceManager.GetString("Status_not_present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal operating mode.
        /// </summary>
        internal static string Status_ok {
            get {
                return ResourceManager.GetString("Status_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to resync to the
        ///RAID volume.
        /// </summary>
        internal static string Status_resync {
            get {
                return ResourceManager.GetString("Status_resync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk is a spare disk on standby.
        /// </summary>
        internal static string Status_spare_inactive {
            get {
                return ResourceManager.GetString("Status_spare_inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermometer malfunction:
        ///turn off ReadyNAS ASAP,
        ///otherwise device may overheat.
        /// </summary>
        internal static string Status_temp_not_ok {
            get {
                return ResourceManager.GetString("Status_temp_not_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main power supply has failed.
        ///UPS is operating on batteries.
        /// </summary>
        internal static string Status_ups_not_ok {
            get {
                return ResourceManager.GetString("Status_ups_not_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume malfunction:
        ///turn off ReadyNAS ASAP.
        /// </summary>
        internal static string Status_volume_not_ok {
            get {
                return ResourceManager.GetString("Status_volume_not_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is in a state where
        ///it needs attention.
        /// </summary>
        internal static string Status_warn {
            get {
                return ResourceManager.GetString("Status_warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  °C.
        /// </summary>
        internal static string String_Celsius {
            get {
                return ResourceManager.GetString("String_Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel .
        /// </summary>
        internal static string String_Channel {
            get {
                return ResourceManager.GetString("String_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAS connection lost.
        /// </summary>
        internal static string String_ConnectionLost {
            get {
                return ResourceManager.GetString("String_ConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan: .
        /// </summary>
        internal static string String_Fan {
            get {
                return ResourceManager.GetString("String_Fan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware:
        ///.
        /// </summary>
        internal static string String_Firmware {
            get {
                return ResourceManager.GetString("String_Firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  GB.
        /// </summary>
        internal static string String_Gb {
            get {
                return ResourceManager.GetString("String_Gb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  GB used of .
        /// </summary>
        internal static string String_Gb_used_of {
            get {
                return ResourceManager.GetString("String_Gb_used_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mac address:
        ///.
        /// </summary>
        internal static string String_MacAddress {
            get {
                return ResourceManager.GetString("String_MacAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no network found.
        /// </summary>
        internal static string String_NoNetwork {
            get {
                return ResourceManager.GetString("String_NoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % used.
        /// </summary>
        internal static string String_percent_used {
            get {
                return ResourceManager.GetString("String_percent_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  rpm.
        /// </summary>
        internal static string String_rpm {
            get {
                return ResourceManager.GetString("String_rpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching.
        /// </summary>
        internal static string String_Searching {
            get {
                return ResourceManager.GetString("String_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sleep.
        /// </summary>
        internal static string String_sleep {
            get {
                return ResourceManager.GetString("String_sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sleeping.
        /// </summary>
        internal static string String_sleeping {
            get {
                return ResourceManager.GetString("String_sleeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature sensor:.
        /// </summary>
        internal static string String_Temperature_sensor {
            get {
                return ResourceManager.GetString("String_Temperature_sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown temperature.
        /// </summary>
        internal static string String_Unknown_Temperature {
            get {
                return ResourceManager.GetString("String_Unknown_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS: .
        /// </summary>
        internal static string String_UPS {
            get {
                return ResourceManager.GetString("String_UPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery: .
        /// </summary>
        internal static string String_UPS_Battery {
            get {
                return ResourceManager.GetString("String_UPS_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume status:
        ///.
        /// </summary>
        internal static string String_Volume {
            get {
                return ResourceManager.GetString("String_Volume", resourceCulture);
            }
        }
    }
}
